### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by dwhiting10** [Position2/jQuery-Simple-MobileMenu#1]
I was wondering what license you are releasing this under?  I don't see a license file.

Thanks!

**Comment by rhenryrobert** [comment]
Hi dwhiting10,

Our plugin is under MIT license.

Now we added the [LICENSE](https://github.com/Position2/jQuery-Simple-MobileMenu/blob/master/LICENSE.md) file.

Thanks!

**Comment by dwhiting10** [comment]
Thanks!
