### ISSUE TITLE
Submenu clicking goes to /#

### ISSUE THREAD

**Issue by panosil79** [Position2/jQuery-Simple-MobileMenu#3]
When you click a submenu sometimes the link is activated instead of opening the submenu

I managed to fix this by adding a `e.preventDefault();` in function showAccordionSubMenu

The final result is

showSlideSubMenu = function(e) {
e.preventDefault();
$("." + smMenu.settings.wrapperClass).scrollTop(0);
$(this).parent().addClass("active").siblings().removeClass("active");
}

Cheers

**Comment by BalajiHP** [comment]
Thank you for your input. We have included your feedback and also removed redundant checks and simplified conditions.
